import { actorPage, closeActors } from './actors';
import { readFile } from 'node:fs/promises';
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.afterEach(closeActors);

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: /가상 사업장으로 체험하기/ }).click();
  await expect(page).toHaveURL(/\/app$/);
});

test('검토 목록 진입·업종·인원·작업 추가·검색·CSV 내려받기', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/app/settings');
  await page.getByRole('link', { name: '업종·인원별 검토 목록', exact: true }).click();
  await expect(page.getByRole('heading', { name: '업종·인원별 검토 목록', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: '업종 묶음', exact: true }).selectOption('food');
  const baseline = await page.locator('.catalog-item').count();
  await page.getByRole('combobox', { name: '인원 구간 · 검토 순서', exact: true }).selectOption('zero');
  await expect(page.getByText(/직접고용 0명이어도/)).toBeVisible();
  await expect(page.locator('.catalog-item')).toHaveCount(baseline);
  await expect(page.locator('#REVIEW-031')).toHaveCount(0);
  await page.locator('.catalog-work > summary').click();
  await page.getByRole('checkbox', { name: '차량·하역', exact: true }).check();
  await expect(page.locator('#REVIEW-031')).toBeVisible();
  await page.getByRole('combobox', { name: '검토 분야', exact: true }).selectOption('inspection');
  await page.getByLabel('항목·질문 검색', { exact: true }).fill('지게차');
  await expect(page.locator('.catalog-item')).toHaveCount(1);
  await page.locator('#REVIEW-031 > summary').click();
  await expect(page.getByText('차량과 보행자 동선·접촉 위험·유도 방법을 확인했는가?')).toBeVisible();
  await page.locator('#REVIEW-031').getByText('근거와 적용 조건 자세히 보기', { exact: true }).click();
  await expect(page.getByRole('link', { name: /산업안전보건기준에 관한 규칙/ })).toHaveAttribute('href', 'https://www.law.go.kr/법령/산업안전보건기준에관한규칙');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: '현재 목록 CSV', exact: true }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toMatch(/^safety-review-.*\.csv$/);
  const csv = await readFile((await download.path())!, 'utf8');
  expect(csv.startsWith('\uFEFF')).toBe(true);
  expect(csv).toContain('REVIEW-031');
  expect(csv).not.toContain('REVIEW-032');
  expect(csv).toContain('음식점·급식 / 0명 / 작업·점검');
  expect(csv).toContain('검토자');
  expect(csv).toContain('적용 여부·전문 검토 대기');
  const doc = await page.request.get('/review-catalog.md');
  expect(doc.ok()).toBe(true);
  expect(await doc.text()).toContain('REVIEW-078');
  expect(errors).toEqual([]);
});

test('목록 모바일·키보드·접근성·검색 없음·운영자 경로', async ({ page }) => {
  await page.goto('/app/checklists');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/catalog-desktop.png' });
  await page.setViewportSize({ width: 360, height: 800 });
  await page.getByLabel('항목·질문 검색', { exact: true }).fill('밀폐공간 출입');
  await expect(page.locator('.catalog-item')).toHaveCount(1);
  const summary = page.locator('#REVIEW-028 > summary');
  await summary.focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#REVIEW-028')).toHaveAttribute('open', '');
  await expect(page.getByText('공간 목록·출입 절차·측정·환기·감시를 검토했는가?')).toBeVisible();
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  expect(audit.violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await summary.scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/catalog-mobile-detail.png' });
  await page.setViewportSize({ width: 320, height: 700 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('항목·질문 검색', { exact: true }).fill('존재하지않는검색어');
  await expect(page.getByRole('heading', { name: '이 검색 조건에서 찾은 후보가 없습니다' })).toBeVisible();
  await expect(page.getByText(/법적 의무가 없다는 뜻은 아닙니다/)).toBeVisible();
  await expect(page.getByRole('button', { name: '현재 목록 CSV', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '전체 후보 다시 보기' }).click();
  await expect(page.getByRole('combobox', { name: '업종 묶음', exact: true })).toHaveValue('all');
  page = await actorPage(page, 'reviewer');
  await expect(page).toHaveURL(/\/ops$/);
  await page.getByRole('link', { name: '법령 준비', exact: true }).click();
  await expect(page.getByRole('heading', { name: '업종·인원별 검토 목록', exact: true })).toBeVisible();
});
