import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { startProfile, completeProfile } from './profile';

test('초보자의 지도 탐색·저장하고 다음·위치 재개·실패 복구', async ({ page }) => {
  await startProfile(page);
  await page.getByRole('button', { name: '알겠어요 · 시작할게요', exact: true }).click();
  await expect(page.getByRole('region', { name: '처음 이용 안내', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('region', { name: '처음 이용 안내', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '처음 이용 안내 다시 보기', exact: true }).click();
  await expect(page.getByRole('region', { name: '처음 이용 안내', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '안내 건너뛰기', exact: true }).click();
  await page.getByRole('link', { name: /먼저 전체 흐름/ }).click();
  await expect(page.getByRole('heading', { name: '전체 관리 지도' })).toBeVisible();
  await page.getByRole('button', { name: /담당자와 관리체계/ }).click();
  await expect(page.locator('#journey-branch-detail')).toContainText('안전보건관리체계');
  await page.getByRole('link', { name: /우리 사업장 알기/ }).click();
  await page.getByLabel('사업장명', { exact: true }).fill('안내 흐름 시험 사업장');
  await page.getByLabel('실제 작업 장소', { exact: true }).fill('시험 시설 1층');
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await expect(page.getByRole('heading', { name: '현장에서 어떤 일을 하나요?' })).toBeVisible();
  await page.getByLabel('실제로 하는 작업').fill('시설 점검과 청소');
  await page.getByLabel('실제 업무에 가까운 업종').selectOption('facility');
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await expect(page.getByRole('heading', { name: '함께 일하는 사람을 알려주세요' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '함께 일하는 사람을 알려주세요' })).toBeVisible();
  await expect(page.getByLabel('현재 직접고용 인원', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await page.getByRole('checkbox', { name: /^입력 내용을 확인했습니다/ }).check();
  await page.getByRole('button', { name: '확인하고 업무 목록 보기' }).click();
  const hero = page.getByRole('region', { name: '지금 함께 할 한 가지' });
  await expect(hero).toContainText('함께 살펴볼 작업을 정해볼까요?');
  await hero.getByRole('link', { name: '작업과 장소 정하기' }).click();
  await page.getByRole('button', { name: '관리 시작', exact: true }).click();
  const help = page.locator('.risk-workflow').getByRole('button', { name: '모르겠어요 · 예시 보기' });
  await help.click();
  await expect(page.getByRole('dialog')).toContainText('설명용 예시');
  await page.keyboard.press('Escape'); await expect(help).toBeFocused();
  await expect(page.getByLabel('함께 살펴볼 작업·장소')).toHaveValue('');
  await page.getByLabel('함께 살펴볼 작업·장소').fill('1층 통로 운반 작업');
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await expect(page.getByRole('heading', { name: '판단 기준', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '판단 기준', exact: true })).toBeVisible();
  await page.getByLabel('위험을 판단할 우리 사업장의 기준').fill('작업자와 기준을 더 확인할 예정');
  await page.route('**/app/tasks/**', route => route.request().method() === 'POST' ? route.abort('failed') : route.continue());
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await expect(page.locator('form[data-save-state="error"]')).toBeVisible();
  await expect(page.getByRole('heading', { name: '판단 기준', exact: true })).toBeVisible();
  await expect(page.getByLabel('위험을 판단할 우리 사업장의 기준')).toHaveValue('작업자와 기준을 더 확인할 예정');
  await page.unroute('**/app/tasks/**');
  await page.getByRole('button', { name: '저장하고 다음', exact: true }).click();
  await expect(page.getByRole('heading', { name: '방법 익히기', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '방법 익히기', exact: true })).toBeVisible();
  await expect(page.locator('.journey-saved-progress')).toContainText('0/7단계');
  await expect(page.locator('#evidence-records')).toContainText('v2');
  await expect(page.locator('.record-statuses')).toContainText('수행 기록 없음');
});

test('저장된 지도·상세 수치 일치와 모바일·도움말·모션 감소', async ({ page }) => {
  await startProfile(page); await completeProfile(page);
  await page.goto('/app/tasks/new?definition=REVIEW-003&workplace=facility');
  await page.getByRole('button', { name: '관리 시작', exact: true }).click();
  await page.locator('.journey-step-picker>summary').click();
  await page.getByRole('navigation', { name: '위험성평가 진행 단계' }).getByRole('button', { name: /위험요인 찾기/ }).click();
  await page.getByRole('button', { name: '위험요인 추가', exact: true }).click();
  await page.getByLabel('어떤 작업인가요?').fill('시험 운반 작업');
  await page.getByLabel('어디에서 하나요?').fill('시험 통로');
  await page.getByLabel('무엇 때문에 어떻게 다칠 수 있나요?').fill('바닥 물기에 미끄러짐');
  await page.getByLabel('누가 영향을 받을 수 있나요?').fill('운반 작업자');
  await page.getByLabel('현재 하고 있는 안전조치').fill('표지 설치');
  await page.getByRole('button', { name: '임시 저장', exact: true }).click();
  await expect(page.locator('.journey-saved-progress')).toContainText('1/7단계');
  await page.getByRole('navigation', { name: '전체 지도에서 현재 위치' }).getByRole('link', { name: '전체 지도' }).click();
  await expect(page.locator('.journey-task').filter({ hasText: '위험성평가와 개선 추적' })).toContainText('기록 준비 1/7단계 · v1');
  await expect(page.locator('.journey-task').filter({ hasText: '위험성평가와 개선 추적' })).toContainText('위험 판단 확인 1건 · 개선·재확인 0건');
  await expect(page.locator('.journey-mini-steps [aria-current="step"]')).toContainText('위험요인 찾기');
  await page.getByRole('button', { name: '목록', exact: true }).click();
  await expect(page.locator('.journey-map-list')).toContainText('기록 준비 1/7단계 · v1');
  await page.getByRole('button', { name: '관계도', exact: true }).click();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  for (const width of [360, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
    await page.screenshot({ path: `test-results/journey-map-${width}.png`, fullPage: true });
  }
  await page.goto('/app');
  await page.getByRole('button', { name: '이 앱은 어떻게 사용하나요?' }).click();
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.screenshot({ path: 'test-results/journey-home-1440.png', fullPage: true });
});
