import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { completeProfile, expertRisk, startProfile } from './profile';

test('평가 회차와 수정 버전을 구분하고 지난 위험·증빙·수행 이력을 보존한다', async ({ page }) => {
  await startProfile(page); await completeProfile(page);
  await page.goto('/app/tasks/new?definition=REVIEW-003&workplace=facility');
  await page.getByRole('button', { name: '관리 시작', exact: true }).click();
  await expect(page.getByRole('heading', { name: '1회차 평가', exact: true })).toBeVisible();
  const first = new URL(page.url()).pathname;
  await expertRisk(page);
  await page.getByLabel('함께 살펴볼 작업·장소').fill('지난 평가의 운반 작업');
  await page.getByRole('navigation', { name: '위험성평가 진행 단계' }).getByRole('button', { name: /위험요인 찾기/ }).click();
  await page.getByRole('button', { name: '위험요인 추가', exact: true }).click();
  await page.getByLabel('어떤 작업인가요?').fill('지난 운반');
  await page.getByRole('navigation', { name: '위험성평가 진행 단계' }).getByRole('button', { name: /위험 판단하기/ }).click();
  await page.getByLabel('현재 위험을 허용할 수 있나요?').selectOption('no');
  if (await page.locator('.journey-optional:not([open]) > summary').count()) await page.locator('.journey-optional:not([open]) > summary').click();
  await page.getByRole('textbox', { name: '담당자', exact: true }).fill('지난 회차 담당자');
  await page.getByLabel('자료 준비 목표일', { exact: true }).fill('2026-10-01');
  await page.getByRole('textbox', { name: '확인 메모', exact: true }).fill('지난 회차에서만 확인한 사실');
  await page.getByRole('button', { name: '임시 저장', exact: true }).click();
  await expect(page.locator('#stored-record')).toContainText('v1');
  await page.getByRole('button', { name: '가상 사진 샘플 연결', exact: true }).click();
  await expect(page.locator('.demo-evidence')).toBeVisible();
  await page.getByLabel('실제 수행일', { exact: true }).fill('2026-09-18');
  await page.getByLabel('직접 확인한 수행 내용').fill('첫 평가에서 직접 살펴본 기록');
  await page.getByRole('button', { name: '수행 기록 저장', exact: true }).click();
  await expect(page.locator('.activity-record')).toContainText('첫 평가에서 직접 살펴본 기록');
  await page.getByRole('navigation', { name: '위험성평가 진행 단계' }).getByRole('button', { name: /준비·방법/ }).click();
  await page.getByLabel('함께 살펴볼 작업·장소').fill('지난 평가의 운반 작업 · 보완');
  await page.getByRole('button', { name: '임시 저장', exact: true }).click();
  await expect(page.locator('#stored-record')).toContainText('v2');
  await page.locator('.new-cycle > summary').click();
  await page.getByRole('checkbox', { name: '기존 기록의 수정이 아니라 새로운 평가를 시작합니다' }).check();
  await page.getByLabel('함께 살펴볼 작업·장소').fill('아직 저장하지 않은 사실');
  await page.getByRole('button', { name: '새 평가 회차 시작', exact: true }).click();
  await expect(page.locator('#task-editor').getByRole('alert')).toContainText('작성 중인 내용을 먼저 임시 저장해주세요');
  expect(new URL(page.url()).pathname).toBe(first);
  await expect(page.getByLabel('함께 살펴볼 작업·장소')).toHaveValue('아직 저장하지 않은 사실');
  await page.getByLabel('함께 살펴볼 작업·장소').fill('지난 평가의 운반 작업 · 보완');
  await page.getByRole('button', { name: '새 평가 회차 시작', exact: true }).click();
  await expect(page.getByRole('heading', { name: '2회차 평가', exact: true })).toBeVisible();
  const second = new URL(page.url()).pathname;
  expect(second).not.toBe(first);
  await expect(page.getByLabel('함께 살펴볼 작업·장소')).toHaveValue('');
  if (await page.locator('.journey-optional:not([open]) > summary').count()) await page.locator('.journey-optional:not([open]) > summary').click();
  await expect(page.getByRole('textbox', { name: '담당자', exact: true })).toHaveValue('');
  await expect(page.getByLabel('자료 준비 목표일', { exact: true })).toHaveValue('');
  await expect(page.getByRole('textbox', { name: '확인 메모', exact: true })).toHaveValue('');
  await expect(page.locator('.task-cycles')).toContainText('개선·재확인 1건');
  await expect(page.locator('.activity-record, .demo-evidence')).toHaveCount(0);
  await page.getByLabel('함께 살펴볼 작업·장소').fill('이번 평가에서 새로 확인할 작업');
  await page.getByRole('button', { name: '임시 저장', exact: true }).click();
  await expect(page.locator('#stored-record')).toContainText('v1');
  await expect(page.locator('#activity-records')).toContainText('수행 기록 없음');
  await page.setViewportSize({ width: 360, height: 900 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path: 'test-results/task-cycle-360.png', fullPage: true });
  await page.goto('/app/map');
  await expect(page.locator('.journey-task').filter({ hasText: '위험성평가와 개선 추적' })).toContainText('2회차');
  await page.goto('/app');
  await expect(page.getByRole('region', { name: '지금 함께 할 한 가지' })).toContainText('지난 1회차');
  await page.goto('/app/documents');
  await expect(page.getByRole('link', { name: /위험성평가와 개선 추적.*1회차/ })).toBeVisible();
  await expect(page.getByRole('link', { name: /위험성평가와 개선 추적.*2회차/ })).toBeVisible();
  await page.goto(first);
  await expect(page.getByRole('link', { name: '현재 2회차로 이동 →' })).toBeVisible();
  await page.locator('.version-history > summary').click();
  await page.getByRole('link', { name: 'v1', exact: true }).click();
  await expect(page.locator('#stored-record')).toContainText('지난 평가의 운반 작업');
  await expect(page.locator('.demo-evidence')).toBeVisible();
  await expect(page.locator('.activity-record')).toContainText('첫 평가에서 직접 살펴본 기록');
});
